"""
hypernetwork.py  —  The core generator H(layer_id, weight_type, z) → W.

Architecture
============
                 ┌─────────────────────────────────────────┐
  layer_id ─────▶│  E_layer  [n_layers × layer_embed_dim]  │──┐
  weight_type ──▶│  E_type   [n_types  × type_embed_dim]   │  │ concat
  latent z  ────▶│  linear(latent_dim → latent_embed_dim)  │──┘
                 └─────────────────────────────────────────┘
                                    │
                              [cond_dim]
                                    │
                         ┌──────────┴──────────┐
                         │   MLP backbone      │
                         │  SiLU activations   │
                         │  LayerNorm between  │
                         └──────────┬──────────┘
                                    │
                             [hidden_last]
                                    │
                      ┌─────────────┼─────────────┐
                      │             │             │
               ┌──────▼──┐   ┌──────▼──┐   ┌──────▼──┐
               │ Head_A   │   │ Head_B   │   │ Head_b  │
               │ →[out,r] │   │ →[r,in]  │   │ →[out]  │
               └──────────┘   └──────────┘   └─────────┘
                      │             │
                      └──── A @ B ──┘
                           W = A @ B   (scaled)

Generated weight:  W = A @ B   ∈ ℝ^{out × in}
Generated bias:    b           ∈ ℝ^{out}

Tensor shapes (default config, hidden_dim=256, ffn_dim=1024, rank=32):
  layer_id      : scalar int  or  LongTensor [B]
  weight_type   : scalar int  or  LongTensor [B]
  z             : None  or  Tensor [B, latent_dim]

  conditioning  : [B, cond_dim]      = [B, 64+64+32] = [B, 160]
  MLP output    : [B, 512]
  Head_A output : [B, out × rank]    → reshape → [B, out, rank]
  Head_B output : [B, rank × in]     → reshape → [B, rank, in]
  W             : [B, out, in]       A @ B  via einsum / bmm
  b             : [B, out]
"""

from __future__ import annotations

import math
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .config import (
    HypernetworkConfig,
    TargetModelConfig,
    WEIGHT_TYPE_INDEX,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

class SiLUMLP(nn.Module):
    """
    Feed-forward network with SiLU activations and pre-norm.

    input_dim → hidden_dims[0] → … → hidden_dims[-1]
    """
    def __init__(self, input_dim: int, hidden_dims: List[int], dropout: float = 0.0):
        super().__init__()
        layers: List[nn.Module] = []
        prev = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev, h))
            layers.append(nn.SiLU())
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
            prev = h
        self.net = nn.Sequential(*layers)
        self.out_dim = prev
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_uniform_(m.weight, a=math.sqrt(5))
                if m.bias is not None:
                    fan_in, _ = nn.init._calculate_fan_in_and_fan_out(m.weight)
                    bound = 1 / math.sqrt(fan_in)
                    nn.init.uniform_(m.bias, -bound, bound)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class SVDWeightHead(nn.Module):
    """
    SVD-based weight generator:  W = U @ diag(s) @ V^T

    U ∈ R^{out × rank} and V ∈ R^{in × rank} are stored as learnable parameters.
    The hypernetwork generates only the rank singular values  s ∈ R^{rank}.

    This is dramatically more parameter-efficient than generating A and B
    directly via linear heads:

    Direct (WeightHead):  backbone_dim × (out*rank + rank*in)
                        = 512 × (256×32 + 32×256) = 8.4 M params  ❌

    SVD (this class):     backbone_dim × rank  +  out*rank  +  in*rank
                        = 512×32 + 256×32 + 256×32 = 32 K params  ✅

    Tensor shapes (out=256, in=256, rank=32, B=4):
        feat  : [B, 512]
        s     : [B, 32]         (generated by the tiny s-head)
        U     : [256, 32]       (stored parameter)
        V     : [256, 32]       (stored parameter)
        W     : [B, 256, 256]   via einsum('or,br,ir->boi', U, s, V)
    """

    def __init__(self, backbone_dim: int, out_dim: int, in_dim: int, rank: int,
                 scale: float = 0.02):
        super().__init__()
        self.out_dim  = out_dim
        self.in_dim   = in_dim
        self.rank     = rank

        # Stored basis matrices — learned but NOT generated per-forward-pass
        self.U = nn.Parameter(torch.empty(out_dim, rank))   # [out, r]
        self.V = nn.Parameter(torch.empty(in_dim,  rank))   # [in,  r]

        # Tiny s-head: backbone_dim → rank  (ONLY this is computed on-the-fly)
        self.s_head = nn.Linear(backbone_dim, rank)

        # Orthogonal init for U, V; small init for s_head
        nn.init.orthogonal_(self.U)
        nn.init.orthogonal_(self.V)
        nn.init.normal_(self.s_head.weight, std=scale / math.sqrt(backbone_dim))
        nn.init.zeros_(self.s_head.bias)

    def forward(self, feat: torch.Tensor) -> torch.Tensor:
        """
        feat : [B, backbone_dim]
        Returns W : [B, out_dim, in_dim]
        """
        s = self.s_head(feat)                                  # [B, rank]
        # W[b, i, j] = Σ_r  U[i,r] * s[b,r] * V[j,r]
        W = torch.einsum("or, br, ir -> boi", self.U, s, self.V)
        return W                                               # [B, out, in]

    @property
    def stored_params(self) -> int:
        return self.U.numel() + self.V.numel()

    @property
    def generated_params(self) -> int:
        return self.rank   # only s is generated


# ---------------------------------------------------------------------------
# Per-layer weight-type head set
# ---------------------------------------------------------------------------

class PerTypeHeads(nn.Module):
    """
    Maintains one SVDWeightHead per matrix weight type.

    Bias vectors are stored as direct parameters (tiny — negligible cost).

    Parameter budget example (hidden=256, ffn=1024, rank=32, backbone=512):
      q_weight head  : 512×32 + 256×32 + 256×32 =  32 768 params
      ffn1_weight    : 512×32 + 1024×32 + 256×32 = 57 344 params
      ffn2_weight    : 512×32 + 256×32 + 1024×32 = 57 344 params
      6 heads total  : ≈ 230 000 params           = ~0.88 MB FP32
      All biases (6 layers × 6 types) ≈ 18 000 params
    """

    def __init__(
        self,
        backbone_dim: int,
        target_cfg:   TargetModelConfig,
        hypernet_cfg: HypernetworkConfig,
    ):
        super().__init__()
        r     = hypernet_cfg.rank
        self.rank        = r
        self.weight_keys = target_cfg.all_weight_keys
        self.matrix_keys = target_cfg.matrix_weight_keys
        self.bias_keys   = target_cfg.bias_weight_keys
        self.shapes      = target_cfg.weight_shapes
        scale            = hypernet_cfg.init_scale
        n_layers         = target_cfg.n_layers

        # ── SVD heads for matrix weights (one per weight type) ────────────────
        self.svd_heads: nn.ModuleDict = nn.ModuleDict()
        for key in self.matrix_keys:
            out_dim, in_dim = self.shapes[key]
            self.svd_heads[key] = SVDWeightHead(backbone_dim, out_dim, in_dim, r, scale)

        # ── Bias vectors stored directly (not generated) — tiny cost ─────────
        # Shape: [n_layers, bias_dim] per bias key
        self.bias_params: nn.ParameterDict = nn.ParameterDict()
        if hypernet_cfg.generate_biases:
            for key in self.bias_keys:
                (b_dim,) = self.shapes[key]
                # One bias per layer
                self.bias_params[key] = nn.Parameter(
                    torch.zeros(n_layers, b_dim)
                )
        self.generate_biases = hypernet_cfg.generate_biases
        self.n_layers        = n_layers

    def forward(
        self,
        feat:            torch.Tensor,    # [B, backbone_dim]
        weight_type_idx: torch.Tensor,    # [B]  LongTensor
        layer_idx:       torch.Tensor,    # [B]  LongTensor  (for bias lookup)
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        Returns (W, b):
            W : [B, out, in]  for matrix keys
            b : [B, out]       for the matching bias (or None)
        """
        unique = weight_type_idx.unique()
        if unique.numel() == 1:
            return self._single_type_forward(feat, weight_type_idx[0].item(), layer_idx)

        # Heterogeneous batch
        B      = feat.size(0)
        device = feat.device
        results: Dict[int, Tuple] = {}
        for t in unique.tolist():
            mask  = (weight_type_idx == t)
            w, b  = self._single_type_forward(feat[mask], int(t), layer_idx[mask])
            results[int(t)] = (mask, w, b)

        first_t    = int(unique[0].item())
        _, w0, b0  = results[first_t]
        W_out = torch.zeros(B, *w0.shape[1:], device=device, dtype=feat.dtype)
        b_out = (torch.zeros(B, *b0.shape[1:], device=device, dtype=feat.dtype)
                 if b0 is not None else None)
        for t, (mask, w, b) in results.items():
            W_out[mask] = w
            if b_out is not None and b is not None:
                b_out[mask] = b
        return W_out, b_out

    def _single_type_forward(
        self,
        feat:      torch.Tensor,
        type_idx:  int,
        layer_idx: torch.Tensor,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        key = self.weight_keys[type_idx]

        if key in self.matrix_keys:
            W = self.svd_heads[key](feat)     # [B, out, in]
            b = None
            if self.generate_biases:
                bias_key = key.replace("_weight", "_bias")
                if bias_key in self.bias_params:
                    # Index bias by layer
                    b = self.bias_params[bias_key][layer_idx]   # [B, b_dim]
            return W, b
        else:
            # Direct bias lookup
            b = self.bias_params[key][layer_idx]   # [B, b_dim]
            return b, None


# ---------------------------------------------------------------------------
# Main Hypernetwork
# ---------------------------------------------------------------------------

class Hypernetwork(nn.Module):
    """
    H(layer_id, weight_type, z) → (W, b)

    Parameters
    ----------
    target_cfg   : config of the model whose weights are generated
    hypernet_cfg : config of this hypernetwork
    """

    def __init__(
        self,
        target_cfg:   TargetModelConfig,
        hypernet_cfg: HypernetworkConfig,
    ):
        super().__init__()
        self.target_cfg   = target_cfg
        self.hypernet_cfg = hypernet_cfg

        n_layers  = target_cfg.n_layers
        n_types   = hypernet_cfg.n_weight_types
        l_dim     = hypernet_cfg.layer_embed_dim
        t_dim     = hypernet_cfg.type_embed_dim
        lat_dim   = hypernet_cfg.latent_dim

        # ── Conditioning embeddings ──────────────────────────────────────────
        self.layer_embed = nn.Embedding(n_layers, l_dim)
        self.type_embed  = nn.Embedding(n_types,  t_dim)
        self.latent_proj = nn.Linear(lat_dim, lat_dim) if lat_dim > 0 else None

        cond_dim = l_dim + t_dim + lat_dim

        # ── MLP backbone ─────────────────────────────────────────────────────
        self.backbone = SiLUMLP(cond_dim, hypernet_cfg.hidden_dims, dropout=0.0)
        backbone_dim  = self.backbone.out_dim

        # ── Per-type output heads ────────────────────────────────────────────
        self.heads = PerTypeHeads(backbone_dim, target_cfg, hypernet_cfg)

        # ── Layer norm on backbone output ───────────────────────────────────
        self.out_norm = nn.LayerNorm(backbone_dim)

        # ── Learnable per-layer scale (helps stability) ──────────────────────
        self.layer_scale = nn.Parameter(
            torch.ones(n_layers, 1) * hypernet_cfg.init_scale
        )

        self._n_params = sum(p.numel() for p in self.parameters())

    # ── forward ──────────────────────────────────────────────────────────────

    def forward(
        self,
        layer_id:    torch.Tensor,           # [B] or scalar
        weight_type: torch.Tensor,           # [B] or scalar
        z:           Optional[torch.Tensor] = None,  # [B, latent_dim] or None
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        Returns
        -------
        W : Tensor [B, out_dim, in_dim]  for matrix weights
            Tensor [B, dim]              for bias vectors
        b : Tensor [B, out_dim]  or  None
        """
        # Normalise scalar inputs to 1-D tensors
        layer_id    = _to_1d(layer_id)
        weight_type = _to_1d(weight_type)
        B = layer_id.size(0)

        device = next(self.parameters()).device
        layer_id    = layer_id.to(device)
        weight_type = weight_type.to(device)

        # Conditioning vector
        e_l = self.layer_embed(layer_id)    # [B, l_dim]
        e_t = self.type_embed(weight_type)  # [B, t_dim]

        if z is not None and self.latent_proj is not None:
            z_proj = self.latent_proj(z.to(device))   # [B, lat_dim]
            cond   = torch.cat([e_l, e_t, z_proj], dim=-1)
        else:
            # Pad latent with zeros if not provided
            lat_pad = torch.zeros(B, self.hypernet_cfg.latent_dim, device=device)
            cond    = torch.cat([e_l, e_t, lat_pad], dim=-1)

        # MLP backbone
        feat = self.backbone(cond)          # [B, backbone_dim]
        feat = self.out_norm(feat)

        # Per-layer scale (index by layer_id)
        scale = self.layer_scale[layer_id]  # [B, 1]
        feat  = feat * scale

        # Output heads  (pass layer_id for per-layer bias lookup)
        W, b = self.heads(feat, weight_type, layer_id)

        return W, b

    # ── convenience: generate ALL weights for one transformer block ──────────

    def generate_layer_weights(
        self,
        layer_idx: int,
        z: Optional[torch.Tensor] = None,
        device: Optional[torch.device] = None,
    ) -> Dict[str, torch.Tensor]:
        """
        Returns a dict  {weight_key: tensor}  for one transformer block.

        Shapes match target_cfg.weight_shapes exactly.
        """
        if device is None:
            device = next(self.parameters()).device

        weights: Dict[str, torch.Tensor] = {}
        for key, idx in WEIGHT_TYPE_INDEX.items():
            lid = torch.tensor([layer_idx], dtype=torch.long)
            tid = torch.tensor([idx],       dtype=torch.long)
            W, b = self(lid, tid, z)    # W : [1, out, in] or [1, out]

            # Squeeze batch dim
            w_sq = W.squeeze(0)
            weights[key] = w_sq

            # Some heads return both W and b in one shot (matrix weight + bias)
            # but PerTypeHeads returns b separately via heads_bias lookup.
            # b is returned only for matrix keys; bias keys return via W directly.
            if b is not None:
                bias_key = key.replace("_weight", "_bias")
                if bias_key in WEIGHT_TYPE_INDEX:
                    weights[bias_key] = b.squeeze(0)

        return weights

    # ── generate weights for all layers ──────────────────────────────────────

    def generate_all_weights(
        self,
        z: Optional[torch.Tensor] = None,
    ) -> List[Dict[str, torch.Tensor]]:
        """Returns list of weight dicts — one per transformer layer."""
        return [
            self.generate_layer_weights(i, z=z)
            for i in range(self.target_cfg.n_layers)
        ]

    # ── size utilities ────────────────────────────────────────────────────────

    @property
    def param_count(self) -> int:
        return self._n_params

    def size_mb(self, dtype_bytes: int = 4) -> float:
        return self._n_params * dtype_bytes / (1024 ** 2)

    def __repr__(self) -> str:  # type: ignore[override]
        return (
            f"Hypernetwork(\n"
            f"  strategy   = {self.hypernet_cfg.strategy}\n"
            f"  rank       = {self.hypernet_cfg.rank}\n"
            f"  backbone   = {self.hypernet_cfg.hidden_dims}\n"
            f"  params     = {self.param_count / 1e6:.3f} M\n"
            f"  size (FP32)= {self.size_mb():.2f} MB\n"
            f"  size (FP16)= {self.size_mb(2):.2f} MB\n"
            f")"
        )


# ---------------------------------------------------------------------------
# Shared-embedding variant (reduces param count further)
# ---------------------------------------------------------------------------

class SharedHypernetwork(Hypernetwork):
    """
    Variant where the MLP backbone parameters are **shared** across weight
    types.  Each type gets only a small adapter (16-dim) injected via FiLM
    (feature-wise linear modulation):

        feat = gamma(type) * backbone(cond) + beta(type)

    This can cut backbone params by ~50 % with minimal accuracy loss.
    """

    def __init__(self, target_cfg: TargetModelConfig, hypernet_cfg: HypernetworkConfig):
        super().__init__(target_cfg, hypernet_cfg)

        n_types  = hypernet_cfg.n_weight_types
        b_dim    = self.backbone.out_dim

        # FiLM modulation per weight type
        self.film_gamma = nn.Embedding(n_types, b_dim)
        self.film_beta  = nn.Embedding(n_types, b_dim)
        nn.init.ones_(self.film_gamma.weight)
        nn.init.zeros_(self.film_beta.weight)

    def forward(
        self,
        layer_id:    torch.Tensor,
        weight_type: torch.Tensor,
        z:           Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        layer_id    = _to_1d(layer_id)
        weight_type = _to_1d(weight_type)
        B           = layer_id.size(0)
        device      = next(self.parameters()).device
        layer_id    = layer_id.to(device)
        weight_type = weight_type.to(device)

        e_l = self.layer_embed(layer_id)
        e_t = self.type_embed(weight_type)
        lat_pad = (z.to(device) if z is not None
                   else torch.zeros(B, self.hypernet_cfg.latent_dim, device=device))
        cond = torch.cat([e_l, e_t, lat_pad], dim=-1)

        feat  = self.backbone(cond)
        feat  = self.out_norm(feat)

        # FiLM conditioning
        gamma = self.film_gamma(weight_type)   # [B, b_dim]
        beta  = self.film_beta(weight_type)    # [B, b_dim]
        feat  = gamma * feat + beta

        scale = self.layer_scale[layer_id]
        feat  = feat * scale

        return self.heads(feat, weight_type, layer_id)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _to_1d(t: torch.Tensor) -> torch.Tensor:
    """Ensure tensor is at least 1-D."""
    if t.dim() == 0:
        return t.unsqueeze(0)
    return t


def build_hypernetwork(
    target_cfg:   TargetModelConfig,
    hypernet_cfg: HypernetworkConfig,
) -> Hypernetwork:
    """Factory that picks the right variant based on config."""
    if hypernet_cfg.share_weights:
        return SharedHypernetwork(target_cfg, hypernet_cfg)
    return Hypernetwork(target_cfg, hypernet_cfg)


def count_parameters(model: nn.Module) -> Dict[str, int]:
    """Returns total, trainable, and non-trainable param counts."""
    total     = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return {
        "total":     total,
        "trainable": trainable,
        "frozen":    total - trainable,
    }
